Resources:
  LocalBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-test-1
  LocalSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: sqs-test-1
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete